[2025-08-07T23:42:39.242+0000] {taskinstance.py:1946} INFO - Dependencies not met for <TaskInstance: bank_data_generation_dag.generate_bank_data scheduled__2025-08-07T21:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-08-07T23:42:39.282+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
